### PR TITLE
Decode h265 frame type

### PR DESCRIPTION
**Pull request by harryz2000**

### CODE REVIEW

**Review by murillo128 — APPROVED** [review]
lgtm, I would appreciate some unit tests for the new parsers

**Comment by harryz2000** [comment]
Yes. I would probably add unit tests in a separate PR for time-being.

**Comment by murillo128** [comment]
is this ready for merge?

**Comment by harryz2000** [comment]
I would need to have a double check. But I have tested. Will change to Ready review once it is confirmed.

**Comment by harryz2000** [comment]
Confirmed ready to merge

**Pull request merged**
