### PR TITLE
Remove RTP header size from media bitrate calculation

### PR DESCRIPTION
**Pull request by harryz2000**
The RTP header size was taken account into the audio/video bitrate calculation, which results in the stats higher than actual media bitrate.

### CODE REVIEW

**Comment by murillo128** [comment]
I don't think we should change the current `totalBytes` and `bitrate` stats, as they are used for multiple things, including bwe and layer selection.

I think we should pass both payload size and rtp header size to the `RTPSource` in two different parameters of the `Update()` method and then add another accumulator for either the payload or the rtp header size (don't think we need both), and then add  `payloadBytes` or `rtpHeaderBytes` and `mediaBitrate`  to the stats

**Comment by harryz2000** [comment]
> I don't think we should change the current `totalBytes` and `bitrate` stats, as they are used for multiple things, including bwe and layer selection.
> 
> I think we should pass both payload size and rtp header size to the `RTPSource` in two different parameters of the `Update()` method and then add another accumulator for either the payload or the rtp header size (don't think we need both), and then add `payloadBytes` or `rtpHeaderBytes` and `mediaBitrate` to the stats

I also thought the stats might be useful for the code. But shouldn't bwe (layer selection) use mediaBitrate as well? For SRT/RTMP, it looks the pure media bitrate is used.

Plus, if we add new stats, I think we would need add them to SRT/RTMP as well. Then would need dash API change to use the new stats.

**Comment by murillo128** [comment]
Lets keep `totalBytes` as it is currently (media+rtp verhead), `bitrate` for media bitrate and add a new `totalBitrate` for media + rtp overhead)

**Comment by harryz2000** [comment]
> Lets keep `totalBytes` as it is currently (media+rtp verhead), `bitrate` for media bitrate and add a new `totalBitrate` for media + rtp overhead)

**Review by murillo128 — APPROVED** [review]
lgtm

**Pull request merged**
